version: '3.8'

services:
  document-processor:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/www/html/logs
    environment:
      - WEBHOOK_URL=https://n8n-with-postgres.srv971849.hstgr.cloud/webhook-test/65e9491c-0d11-415d-8f85-09a66447a6fd
      - MAX_FILE_SIZE=10485760
    restart: unless-stopped

  # Opcional: Base de datos si necesitas almacenar información
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: document_processor
      MYSQL_USER: processor
      MYSQL_PASSWORD: processor123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: